#!/bin/sh

set -u
set -e

mkdir src build devel logs

catkin init
catkin config --extend /opt/ros/melodic --merge-devel --cmake-args -DCMAKE_BUILD_TYPE=Release

cd src
git clone https://github.com/ethz-asl/voxblox.git
wstool init . ./voxblox/voxblox_https.rosinstall
wstool update

git clone https://github.com/ethz-asl/catkin_boost_python_buildtool.git
git clone https://github.com/ethz-asl/numpy_eigen.git


#git clone https://github.com/catkin/catkin_simple.git
#git clone https://github.com/ethz-asl/eigen_catkin.git
#git clone https://github.com/ethz-asl/eigen_checks.git
#git clone https://github.com/ethz-asl/gflags_catkin.git
#git clone https://github.com/ethz-asl/glog_catkin.git
#git clone https://github.com/ethz-asl/minkindr.git
#git clone https://github.com/ethz-asl/protobuf_catkin.git

