#!/bin/sh

set -u
set -e

export ROS_DISTRO=${1:-"melodic"}

USER=$(docker info 2>&1 | grep -e '^ Username: ' | sed -e 's/ Username: \(.*\)/\1/')
DIR=$(dirname $(readlink -f $0))
IMAGE=${USER}/$(basename $DIR)-${ROS_DISTRO}

echo building ${IMAGE}
exec docker build --build-arg ROS_DISTRO --tag ${IMAGE} .
