#!/bin/sh

set -u
set -e

USER=$(docker info 2>&1 | grep -e '^ Username: ' | sed -e 's/ Username: \(.*\)/\1/')
DIR=$(dirname $(readlink -f $0))
IMAGE=$(basename $DIR)
export ROS_DISTRO=${ROS_DISTRO:-melodic}
exec docker build --build-arg ROS_DISTRO --tag $USER/${IMAGE}-${ROS_DISTRO} . $@
