#!/bin/sh

USER=$(docker info 2>&1 | grep -e '^ Username: ' | sed -e 's/ Username: \(.*\)/\1/')
DIR=$(dirname $(readlink -f $0))
ROS_DISTRO=${1:-"melodic"}
IMAGE=$(basename $DIR)-${1:-"melodic"}

if [ "$#" -gt "0" ]; then
	shift
fi

echo running ${IMAGE}
exec docker run -e DISPLAY -e QT_X11_NO_MITSHM=1 -v "/tmp/.X11-unix:/tmp/.X11-unix" --gpus all --privileged --rm -it --network host $USER/$IMAGE $@
