#!/bin/sh

USER=$(docker info 2>&1 | grep -e '^ Username: ' | sed -e 's/ Username: \(.*\)/\1/')
DIR=$(dirname $(readlink -f $0))
IMAGE=$(basename $DIR)

exec docker run -e DISPLAY -e QT_X11_NO_MITSHM=1 -v "/tmp/.X11-unix:/tmp/.X11-unix" --gpus all --privileged -it $USER/$IMAGE $@
